navikt/veilarbdialog

- src/main/java/no/nav/fo/veilarbdialog/rest/KasserRessurs.java
Space funker ikke med naiserator oppsettet
> FO-2655: Split på komma

- README.md
> prodsetting

- src/test/java/no/nav/fo/veilarbdialog/util/MessageQueueUtilsTest.java
La til manglende test for MessageQueueUtils.
Danner grunnlag for sammenligning med bruk av XmlMapper i Spring Boot.
> La til test for MessageQueueUtils

- src/main/java/no/nav/fo/veilarbdialog/service/DialogDataService.java
- src/main/java/no/nav/fo/veilarbdialog/service/KladdService.java
- src/test/java/no/nav/fo/veilarbdialog/service/ServiceConfig.java
Bytter ut AktorregisterClient med AktorOppslagClient.
> Fiks henting av bønne for AktorOppslagClient

- src/main/java/no/nav/fo/veilarbdialog/kvp/KontorsperreFilter.java
- src/main/java/no/nav/fo/veilarbdialog/rest/DialogRessurs.java
- src/main/java/no/nav/fo/veilarbdialog/rest/RestMapper.java
- src/main/java/no/nav/fo/veilarbdialog/service/DialogDataService.java
- src/test/java/no/nav/fo/veilarbdialog/db/dao/DialogFeedDAOTest.java
- src/test/java/no/nav/fo/veilarbdialog/rest/RestServiceTest.java
* Flytter logikk ut av Controlleren
* Gjør tilgangskontrollen mer synlig(putter øverst i servicen, renamer "kvpFilter" som er relatert til tilgangskontroll)
* Refaktorerer litt ( `finnDialogId()` opprettet dialog når den ikke fantes, det syns jeg var uryddig, har derfor flyttet det ut)
* Har renamet diverse som jeg hadde ulogiske navn
* integrasjonstest som går mot restendepunktet og tester hele integrasjonen i appen, med noen få unntak
> Rydde i rest controller

- src/main/java/no/nav/fo/veilarbdialog/service/DialogDataService.java
- src/test/java/no/nav/fo/veilarbdialog/rest/DialogRessursTest.java
* Fikser en bug
* Fikser tester som var kommentert ut, renamer tester for lesbarhet
> Fikser en bug som skaper nullpointer når man lager dialog knyttet til aktivitet

- src/main/java/no/nav/fo/veilarbdialog/config/MessageQueueConfig.java
- src/main/java/no/nav/fo/veilarbdialog/db/dao/DataVarehusDAO.java
- src/test/java/no/nav/fo/veilarbdialog/db/dao/DialogFeedDAOTest.java
- src/test/java/no/nav/fo/veilarbdialog/service/KafkaTestConfig.java
La til manglende config i KafkaTestConfig også (kunne ikke kjøre DialogFeedDAOTest).
> Fjernet noen bugs rapportert fra SonarCloud.

- src/main/java/no/nav/fo/veilarbdialog/db/dao/DialogDAO.java
- src/main/java/no/nav/fo/veilarbdialog/domain/DialogData.java
- src/main/java/no/nav/fo/veilarbdialog/metrics/FunksjonelleMetrikker.java
- src/main/java/no/nav/fo/veilarbdialog/rest/DialogRessurs.java
- src/main/java/no/nav/fo/veilarbdialog/rest/RestMapper.java
- src/main/java/no/nav/fo/veilarbdialog/service/DialogDataService.java
- src/main/java/no/nav/fo/veilarbdialog/service/DialogStatusService.java
- src/test/java/no/nav/fo/veilarbdialog/db/dao/StatusDAOTest.java
- src/test/java/no/nav/fo/veilarbdialog/service/DialogStatusServiceTest.java
Fikser diverse som dukket opp når jeg skulle forstå koden for å fikse bug.
* Sonar cloud code smells
* eldsteUlesteTidspunktForVeileder renamet fordi det er i realiteten tidspunktet for den nyeste henvendelsen som veileder ikke har lest
* Endepunktet for ferdigbehandlet gjorde unødvendig om til DialogStatus objekt når bare en bool kreves
* Ingen funksjonelle endringer, selve bugfixen kommer i neste pr
> Code smells

- src/main/java/no/nav/fo/veilarbdialog/db/dao/DialogDAO.java
- src/main/java/no/nav/fo/veilarbdialog/rest/AdminController.java
- src/main/java/no/nav/fo/veilarbdialog/service/KafkaRepubliseringService.java
- src/test/java/no/nav/fo/veilarbdialog/db/dao/DialogDAOTest.java
Endepunkt for republisering av Kafka meldinger på topic for endring på dialog. Republiserer for alle brukere som har aktiv dialog.
> Admin endepunkt for republisering av Kafka-meldinger

- src/main/resources/application.yaml
> topic config

- src/main/java/no/nav/fo/veilarbdialog/brukernotifikasjon/BrukernotifikasjonService.java
- src/main/java/no/nav/fo/veilarbdialog/eskaleringsvarsel/EskaleringsvarselService.java
- src/test/java/no/nav/fo/veilarbdialog/eskaleringsvarsel/EskaleringsvarselControllerTest.java
> tekster varsel og oppgave

- src/main/java/no/nav/fo/veilarbdialog/eskaleringsvarsel/EskaleringsvarselController.java
- src/test/java/no/nav/fo/veilarbdialog/eskaleringsvarsel/EskaleringsvarselControllerTest.java
Gjeldende skal kunne kalles for både ekstern og intern bruker
> Gjeldende skal kunne kalles for både ekstern og intern bruker

- src/main/java/no/nav/fo/veilarbdialog/brukernotifikasjon/BrukernotifikasjonService.java
brukernotifikasjon synlig 1 mnd på ditt nav
> brukernotifikasjon synlig 1 mnd på ditt nav

- src/main/java/no/nav/fo/veilarbdialog/metrics/FunksjonelleMetrikker.java
- src/main/java/no/nav/fo/veilarbdialog/service/ScheduleRessurs.java
Telle oppgave vs beskjed, og kanVarsles vs kanIkkeVarsles
> Brukernotifikasjonsmetrikker første del

- src/main/java/no/nav/fo/veilarbdialog/db/dao/VarselDAO.java
- src/main/java/no/nav/fo/veilarbdialog/service/ScheduleRessurs.java
- src/main/resources/application.yaml
- src/test/java/no/nav/fo/veilarbdialog/rest/DialogBeskjedTest.java
- src/test/resources/application.yaml
Ikke sende ut varsler for henvendelser eldre enn 48 timer
> Ikke sende ut varsler for henvendelser eldre enn 48 timer

- nais/alerts-prod.yaml
Kun 3-dagers terskel på 5** feil
> Endre alarm

- src/main/java/no/nav/fo/veilarbdialog/config/AktorClientConfig.java
Tilgang gitt i prod: https://github.com/navikt/pdl/commit/7e86725ec5d4e675d142da6efb4ac8f3fce71a39
Tilgang gitt i Jira: https://jira.adeo.no/plugins/servlet/desk/portal/541/FAGSYSTEM-242240
> Pdl AzureAd M2M

- src/main/java/no/nav/fo/veilarbdialog/config/FilterConfig.java
- src/main/resources/application.yaml
Prøver også å rydde litt i application.yaml
> Fjerner Auth mulighet for OpenAm Veileder

- pom.xml
- src/main/java/no/nav/fo/veilarbdialog/clients/veilarbperson/VeilarbpersonClientImpl.java
- src/main/java/no/nav/fo/veilarbdialog/clients/veilarbperson/VeilarbpersonConfig.java
- src/main/java/no/nav/fo/veilarbdialog/config/AktorClientConfig.java
- src/main/java/no/nav/fo/veilarbdialog/service/ServiceConfig.java
- src/test/java/no/nav/fo/veilarbdialog/config/ApplicationTestConfig.java
Må vente på prodseting av veilarbperson https://github.com/navikt/veilarbperson/pull/204
> Bruker azure M2M mot veilarbperson

- .github/workflows/kafka-topic-dev.yml
- .github/workflows/kafka-topic-prod.yml
- nais/kafka-topic/dev/endring-paa-dialog-v1-topic.yaml
- nais/kafka-topic/prod/endring-paa-dialog-v1-topic.yaml
- src/main/java/no/nav/fo/veilarbdialog/config/kafka/aiven/KafkaAivenConfig.java
- src/main/java/no/nav/fo/veilarbdialog/service/KafkaProducerService.java
- src/main/resources/application.yaml
- src/test/java/no/nav/fo/veilarbdialog/service/KafkaProducerServiceTest.java
- src/test/java/no/nav/fo/veilarbdialog/util/KafkaTestService.java
- src/test/resources/application.yaml
Co-authored-by: Alexander Gård <alex.gaard@hotmail.com>
Co-authored-by: Izis Frøyhov <izis.froyhov@nav.no>
> Publiser endringPaaDialog til Aiven

- src/main/java/no/nav/fo/veilarbdialog/config/EnhanceSecureLogsFilter.java
- src/main/java/no/nav/fo/veilarbdialog/config/FilterConfig.java
- src/main/java/no/nav/fo/veilarbdialog/config/SecureRequestLoggerFilter.java
> fiks securelogs filter

- .github/workflows/deploy-feature-branch.yml
- nais/nais-dev.yaml
- nais/nais-prod.yaml
- src/main/java/no/nav/fo/veilarbdialog/config/FilterConfig.java
- src/main/resources/application.yaml
- src/test/resources/application.yaml
- Remove loginserviceIdportenConfig
- Add write package permission
> remove loginserviceIdportenConfig

- nais/nais-dev-gcp.yaml
- nais/nais-prod-gcp.yaml
Reverts navikt/veilarbdialog#307
> Revert "Bruk veilarboppfolging i gcp"

- nais/nais-dev-gcp.yaml
- nais/nais-prod-gcp.yaml
Reverts navikt/veilarbdialog#308
> Revert "Revert "Bruk veilarboppfolging i gcp""

- src/main/java/no/nav/fo/veilarbdialog/domain/NyMeldingDTO.java
- src/main/java/no/nav/fo/veilarbdialog/rest/DialogRessurs.java
- **Legg til litt swagger annotations**
- **Fullfør setning**
- **Mer beskrivelser**
- **Add security scheme**
> Oppdater swagger
